# -*- coding: utf-8 -*-
"""Weather_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wj3cgmd5nnlBdQFYc9NAuzhsp96xwFiK
"""

def calculate_heat_index(temperature, humidity):
    try:
        heat_index = temperature + (0.55 * (1 - (humidity / 100)) * (temperature - 14.5))
        return round(heat_index, 2)
    except Exception as e:
        print(f"Error in calculation: {e}")
        return None

"""1. Hardcoded"""

temperature = 30  # degrees Celsius
humidity = 70  # percentage
wind_speed = 15  # km/h

heat_index = calculate_heat_index(temperature, humidity)
print(f"Temperature: {temperature}°C, Humidity: {humidity}%, Wind Speed: {wind_speed} km/h")
print(f"Heat Index: {heat_index}°C")

"""2. Keyboard input"""

try:
    temperature = float(input("Enter temperature in °C: "))
    humidity = float(input("Enter humidity in percentage: "))
    wind_speed = float(input("Enter wind speed in km/h: "))

    heat_index = calculate_heat_index(temperature, humidity)
    print(f"Temperature: {temperature}°C, Humidity: {humidity}%, Wind Speed: {wind_speed} km/h")
    print(f"Heat Index: {heat_index}°C")
except ValueError as e:
    print("Invalid input! Please enter numeric values.")

"""3.	Reading Variables from a File"""

try:
    with open("weather_data.txt", "r") as file:
        line = file.readline().strip()

        data = [float(value.strip()) for value in line.split(",")]

        if len(data) == 3:
            temperature, humidity, wind_speed = data
            heat_index = calculate_heat_index(temperature, humidity)
            print(f"Temperature: {temperature}°C, Humidity: {humidity}%, Wind Speed: {wind_speed} km/h")
            print(f"Heat Index: {heat_index}°C")
        else:
            print("Error: The file must contain exactly three comma-separated values.")
except Exception as e:
    print(f"Error reading the file: {e}")

try:
    with open("weather_data_multi.txt", "r") as file:
        for line in file:

            cleaned_line = line.strip().rstrip(",")
            data = cleaned_line.split(",")

            if len(data) == 3:
                try:
                    temperature, humidity, wind_speed = map(float, data)
                    heat_index = calculate_heat_index(temperature, humidity)
                    print(f"Temperature: {temperature}°C, Humidity: {humidity}%, Wind Speed: {wind_speed} km/h")
                    print(f"Heat Index: {heat_index}°C\n")
                except ValueError as ve:
                    print(f"Invalid data in line: '{line.strip()}' - {ve}")
            else:
                print(f"Invalid line format: '{line.strip()}'. Expected exactly three comma-separated values.")
except Exception as e:
    print(f"Error reading the file: {e}")